### ISSUE TITLE
tool10urltarget won't work

### ISSUE THREAD

**Issue by it-ben** [An-dir/dokuwiki-plugin-iphelper#1]
no IP-Adress is handed to a link

**Comment by An-dir** [comment]
seems to be a mistake in line 46 in action.php
fixed line will be updated soon.
normally it should look like:
`                   if (strlen($tool10name) > 1) {$tool10url = $this->getConf('tool10url');$tool10urltarget = $this->getConf('tool10urltarget'); $tool10html = "<a href=\"". $tool10url ."\" target=\"". $tool10urltarget ."\">" . $tool10name . "</a><br>";}					`

no testings done till now.

**Comment by An-dir** [comment]
Fixed with todays update. Only line 46 needed to be fixed in action.php. Dokuwiki should show you the newest update automatically after some time, or go to "seach and install" dokuwiki search for iphelper and click update there.

An-Dir
