### ISSUE TITLE
Compatible with 2020-06-01 ?

### ISSUE THREAD

**Issue by Megachip** [An-dir/dokuwiki-plugin-iphelper#2]
```
PHP Fatal error:  Declaration of action_plugin_iphelper::register() must be compatible with dokuwiki\Extension\ActionPlugin::register(Doku_Event_Handler $controller) in /volume1/web/dokuwiki/lib/plugins/iphelper/action.php on line 422

Fatal error: Declaration of action_plugin_iphelper::register() must be compatible with dokuwiki\Extension\ActionPlugin::register(Doku_Event_Handler $controller) in /volume1/web/dokuwiki/lib/plugins/iphelper/action.php on line 422
```

**Comment by An-dir** [comment]
Confirmed that error in the new DokuWiki Version "Hogfather"
have to take a closer look. In the meanwhile stay at earlier dokuwiki versions

**Comment by An-dir** [comment]
made a fix for two errors now. some functions had to be changed so that they now fit to current documentation. currently the plugin still does not work due to an error with missing/wrong jQuery.
For now updating dokuwiki with current build of iphelper, your installation wont crash anymore, but plugin is without any dynamic function.

**Comment by An-dir** [comment]
Have an "ugly" fix that may make more compatibility issues.
Update to the latest version of my plugin, add the following line in a new line after "<<<TEXT"

`<script src="http://code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>`

I still don't know why jQuery does not work anymore.

**Comment by An-dir** [comment]
Found a new Option that causes the last jQuery problem. 
Just use latest version (uploaded a few minutes ago) and disable "defer_js" in dokuwiki "Feature Flags" within "configuration settings" page.
In "dokuwiki.php" it is the line
`$conf['defer_js'] = 0;`

can someone else confirm it is running in production environment?

**Comment by An-dir** [comment]
UPDATE:
NEW Version of the plugin with seperate javascript file and some more code markup fixes made it work again. Just replace old plugin files.

Keep me updated if any issues regarding latest dokuwiki update are now resolved

**Comment by An-dir** [comment]
Updated version works pretty good in all common dokuwiki versions. Bug seems to be fixed completely.
